In [1]:
%pip install pandas lxml --upgrade

Collecting pandas
  Using cached pandas-3.0.1-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting lxml
  Downloading lxml-6.0.2-cp313-cp313-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl.metadata (3.6 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.3-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.1-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
Downloading lxml-6.0.2-cp313-cp313-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl (5.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 15.0 MB/s eta 0:00:00a 0:00:01
Downloading numpy-2.4.3-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 13.1 MB/s eta 0:00:0000:0100:01
Installing collected packages: numpy, lxml, pandas
Successfully installed lxml-6.0.2 numpy-2.4.3 pandas-3.0.1

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

URL = "https://en.wikipedia.org/wiki/List_of_world_records_in_swimming"

In [5]:
import gazpacho
import io

AGENT = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36",
}

html = gazpacho.get(URL, headers=AGENT)
tables = pd.read_html(io.StringIO(html))

In [7]:
tables[0].head()

,Event,Time,Unnamed: 2,Name,Nationality,Date,Meet,Location,Ref
0,50m freestyle,20.91,ss,César Cielo,Brazil,18 December 2009,Brazilian Championships,"São Paulo, Brazil",[9][10][11][12]
1,100m freestyle,46.40,NaN,Pan Zhanle,China,31 July 2024,Olympic Games,"Paris, France",[13]
2,200m freestyle,1:42.00,ss,Paul Biedermann,Germany,28 July 2009,World Championships,"Rome, Italy",[14][15][16]
3,400m freestyle,3:39.96,NaN,Lukas Märtens,Germany,12 April 2025,Swim Open Stockholm,"Stockholm, Sweden",[17]
4,800m freestyle,7:32.12,ss,Zhang Lin,China,29 July 2009,World Championships,"Rome, Italy",[18][19]

In [9]:
df = tables[0][["Event", "Time"]]
df.head()

            Event     Time
0   50m freestyle    20.91
1  100m freestyle    46.40
2  200m freestyle  1:42.00
3  400m freestyle  3:39.96
4  800m freestyle  7:32.12

In [10]:
df = df[~df["Event"].str.contains("relay")]

In [13]:
df = df.set_index("Event")

In [15]:
df.to_dict()

{'Time': {'50m freestyle': '20.91',
  '100m freestyle': '46.40',
  '200m freestyle': '1:42.00',
  '400m freestyle': '3:39.96',
  '800m freestyle': '7:32.12',
  '1500m freestyle': '14:30.67',
  '50m backstroke': '23.55',
  '100m backstroke': '51.60',
  '200m backstroke': '1:51.92',
  '50m breaststroke': '25.95',
  '100m breaststroke': '56.88',
  '200m breaststroke': '2:05.48',
  '50m butterfly': '22.27',
  '100m butterfly': '49.45',
  '200m butterfly': '1:50.34',
  '200m individual medley': '1:52.69',
  '400m individual medley': '4:02.50'}}

In [19]:
records = {}
records["LC Men"] = df.to_dict()["Time"]

In [20]:
records

{'LC Men': {'50m freestyle': '20.91',
  '100m freestyle': '46.40',
  '200m freestyle': '1:42.00',
  '400m freestyle': '3:39.96',
  '800m freestyle': '7:32.12',
  '1500m freestyle': '14:30.67',
  '50m backstroke': '23.55',
  '100m backstroke': '51.60',
  '200m backstroke': '1:51.92',
  '50m breaststroke': '25.95',
  '100m breaststroke': '56.88',
  '200m breaststroke': '2:05.48',
  '50m butterfly': '22.27',
  '100m butterfly': '49.45',
  '200m butterfly': '1:50.34',
  '200m individual medley': '1:52.69',
  '400m individual medley': '4:02.50'}}

In [21]:
RECORDS = (0, 1, 3, 4)   # Update these values as required (these are valid as of Wednesday 28, 2026).

COURSES = ("LC Men", "LC Women", "SC Men", "SC Women")

records = {}
for table, course in zip(RECORDS, COURSES):
    df = tables[table][["Event", "Time"]]
    df = df[~df["Event"].str.contains("relay")]
    df = df.set_index("Event")
    records[course] = df.to_dict()["Time"]